import { HamburgerMenuIcon } from '@radix-ui/react-icons';
import {
  Home,
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  Package,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LogIn,
  LucideIcon,
  Moon,
  MoreVertical,
  Plus,
  Settings,
  ShoppingCart,
  SunMedium,
  Trash,
  User,
  User2Icon,
  UserX2Icon,
  X,
  UserRoundCog
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  dashboard: Home,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  product: Package,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  resturant: HamburgerMenuIcon,
  role: UserRoundCog,
  shoppingCart: ShoppingCart,

  check: Check
};
